### ISSUE TITLE
Incorrect time offset

### ISSUE THREAD

**Issue by morokin** [Vertamedia/chtable#2]
Hi, I downloaded latest release of this plugin and got an issue: \
I have time set to UTC both in relevant database column and in Grafana, but time in table shows with 3 hours offset, but if I'm setting Local browser time in Grafana - time in table became correct.  I had no issues like this with other table plugins.

Have a great day
Evgeny

**Comment by hagen1778** [comment]
Hi @morokin 
CHtable is as simple as default panel `table`. Frankly, it's modified version of it with some cache features. And it should behave as original panel `table` does. 

To make Grafana do timeshifts according to the timezone you must treat time value as a `Date`. Let's make an experiment with selecting `DateTime` column into `CHTable`:
![pic1](https://user-images.githubusercontent.com/2902918/41705347-63d07344-7541-11e8-897d-ec04a7187ba7.png)

Treat `DateTime` column as a `Date` in `ColumnStyles`:
![pic2](https://user-images.githubusercontent.com/2902918/41705455-ad3b634a-7541-11e8-8e68-3a70cdc6bdef.png)

And try to configure timezone. It should do adjustments according to TZ changes, as default panel `Table` do.

**Comment by morokin** [comment]
Hi @hagen1778 
Appreciate your quick answer, first, looks like my issue description wasn't completely clear. I have checked this with default Grafana table and with some other tables and I have the same issue so it's clearly not limited by CHtable, but I'll try to explain just to be sure. I have EventDateTime (DateTime) column in UTC in database, and I want to see exactly UTC time in the table, but when I configuring column style for the relevant column as Date and configuring dashboard timezone as UTC, the time column in Grafana table shifts from UTC time to the time with local timezone offset. I double-checked this with one of our other tables with some other datasource - for example InfluxDB source:
time in DB - UTC
relevant column set as Date in Grafana table
Dashboard set to display UTC time
Result - UTC time in table

When I configuring dashboard to show local time - table switching to display time with timezone offset.

So looks like it can be clickhouse datasource issue, it takes time from database as local time not as UTC time by default and since that the whole logic of dashboard timezone setting works oppositely than in some other datasources.

Can you please somehow confirm or deny, so I'll be able to open relevant issue in datasource repo?

**Comment by hagen1778** [comment]
If I understood it rightly InfluxDB, MySQL and PostgreSQL are storing datetime with timezone while CH don't. So when we query timestamp from, for example, MySQL the response will be:
`{"results":{"A":{"refId":"A","meta":{"rowCount":1,"sql":"SELECT  datetime, aid from events;\n"},"series":null,"tables":[{"columns":[{"text":"datetime"},{"text":"aid"}],"rows":[["2018-06-21T10:58:18Z",1]]}]}}}`

Grafana is able to understand datetime `2018-06-21T10:58:18Z` correctly. But CH will return following result:
```
"data":
	[
		{
			"datetime": "2018-06-21 10:58:00",
			"Aid": 2
		}
...
```
Where datetime goes without timezone. Grafana will do offset without knowing that timestamp is already in UTC.

As a workaround, you can stop using `Date` column type in Grafana, do all time-related converts in the query and treat datetime values as String.

**Comment by morokin** [comment]
Hi,

> As a workaround, you can stop using Date column type in Grafana, do all time-related conversions in the query and treat datetime values as String.
I have this setup working perfectly well: 
![screenshot 2018-06-21 23 00 21](https://user-images.githubusercontent.com/6605568/41743405-53b7f6f4-75a9-11e8-8593-c7f77cc5159d.png)

![screenshot_2018-06-21_23_00_45](https://user-images.githubusercontent.com/6605568/41743366-3abac1d6-75a9-11e8-80d0-68d26ec5f7fe.png)

![screenshot 2018-06-21 23 01 06](https://user-images.githubusercontent.com/6605568/41743347-29040ee8-75a9-11e8-8b44-f8e6df5f5c1e.png)
Where TS contains timestamp including ms:
```
EventDate Date materialized toDate(round(TS/1000)),
EventDateTime DateTime materialized toDateTime(round(TS/1000)),
TS UInt64,
```
```
:) select TS from test.test limit 5

SELECT TS
FROM test.test
LIMIT 5

┌────────────TS─┐
│ 1522594950246 │
│ 1522594992336 │
│ 1522595372003 │
│ 1522595410263 │
│ 1522595550821 │
└───────────────┘

5 rows in set. Elapsed: 0.002 sec.
```

Time perfectly adjusts on dashboard timezone changing despite to no timezone specified.
As we realised this is definitely not CHtable issue, and if you think it is not related to clickhouse datasource feel free to close this issue.

Thanks

**Comment by morokin** [comment]
Small update, with select toDateTime(round(TS/1000)) in table query - same issue with offset - so looks like Grafana takes timestamp by default as UTC and DateTime without timezone as local time - and this makes perfect sense.

Thank you again.

**Comment by AngelLittleChaochao** [comment]
Since clickhouse returned the DateTime without timezone information, let's format the DateTime to "UTC" or your clickhouse data time zone. Then it works.

formatDateTime(event_time, '%Y-%m-%dT%TZ')

SELECT
    formatDateTime(event_time, '%Y-%m-%dT%TZ') as t,
    count()
from [YOUR_TABLE]
