### ISSUE TITLE
develop plugin

### ISSUE THREAD

**Issue by HediDlp** [Vertamedia/chtable#3]
Hi,
i install grafana and then:
-clone the plugin into data/plugins directory
-yarn install
-grunt
-grunt watch
-do some changes in source
but changes not affected. How can i solve this problem?
thanks.

**Comment by hagen1778** [comment]
Hi @HediDlp 

Grafana "reads" plugins from `dist` folder. Make sure that changes you made at `src` were transformed to `dist` folder by `grunt`. If it so, and there are still no changes - try to disable cache in your browser (can be done easily via developer tools). Changes from `plugin.json` can be visible only after Grafana restart.

**Comment by HediDlp** [comment]
thanks. i cheked these but not work again. is there any other configureations that may be i missed? i follow instructions described here(https://github.com/grafana/typescript-template-datasource)

**Comment by hagen1778** [comment]
Check if `Grunt` works fine and there are no errors. Or try to make some changes in `dist` folder to see if Grafana updated the plugin.

**Comment by HediDlp** [comment]
sorry, can you please clone the plugin and make some changes to check it work.
thanks.

**Comment by hagen1778** [comment]
I'm not sure I understand your question. You want me to apply some changes or just prove that it's possible?

**Comment by HediDlp** [comment]
yes, to prove that its possible. It would be really great help. I really don't know what is will go wrong.

**Comment by hagen1778** [comment]
I tired locally and changes were applied. What did I do:
* updated Grafana config with folder where plugin source code placed:
```
# Directory where grafana will automatically scan and look for plugins
plugins = /Users/hagen/gopath/src/github.com/Vertamedia/chtable
```
* restarted Grafana and checked its output:
```
DBUG[08-01|09:56:34] Plugins: Adding route                    logger=http.server route=/public/plugins/vertamedia-chtable dir=/Users/hagen/gopath/src/github.com/Vertamedia/chtable/dist
```
* opened Grafana's in browser an created dashboard with `chtable` plugin
* made some changes in `src/editor.html`
* run `grunt`
* checked changes in browser

**Comment by HediDlp** [comment]
thanks a lot hagen i can change editor.html so. but my problem is that why changes to column_options.html didn't applied?

**Comment by hagen1778** [comment]
You were right, there was a wrong `templateURL` path to templates. I fixed it in master. Thank you for pointing this to me.

**Comment by HediDlp** [comment]
Thanks for your great help too.
